# Generated by Django 4.1 on 2022-08-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.CharField(max_length=6)),
                ('nombreResponsable', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=250)),
            ],
        ),
    ]
